import {paintMap,biomeNames} from './renderer.js';
const $=id=>document.getElementById(id),canvas=$('world'),ctx=canvas.getContext('2d');
const terrain=document.createElement('canvas');
let state=null,tool='inspect',zoom=1,ox=0,oy=0,fitted=false,token='',selected=null,dragging=null,layer='natural';
let preview=null,previewSequence=0,epoch=null,geography='continents',optionsReady=false,casting=false,hover=null;
const dialog=$('world-setup');
function notice(text){$('notice').textContent=text;$('notice').style.display='block';clearTimeout(notice.timer);notice.timer=setTimeout(()=>$('notice').style.display='none',5000);}
async function command(data){const r=await fetch('/api/command',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify(data)});const result=await r.json();if(!r.ok)throw Error(result.error);return result.result;}
function act(data){return command(data).catch(e=>notice(e.message));}
function setTool(id){tool=id;document.querySelectorAll('[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===id));}
function powers(){if(!state)return;$('tools').replaceChildren();const list=[{id:'inspect',icon:'⌕',name:'Inspect'},...state.powers.filter(p=>p.group===$('power-group').value)];for(const p of list){const b=document.createElement('button');b.dataset.tool=p.id;const icon=document.createElement('b');icon.textContent=p.icon;b.append(icon,document.createTextNode(p.name));b.onclick=()=>setTool(p.id);$('tools').append(b);}setTool('inspect');}
$('power-group').onchange=powers;
$('radius').oninput=()=>$('radius-value').textContent=$('radius').value;
$('pause').onclick=()=>state&&!state.setup_required&&act({action:'pause',value:!state.runtime.paused});
$('speed').onchange=e=>act({action:'speed',value:Number(e.target.value)});
$('save').onclick=async()=>{try{await command({action:'save'});notice('World and neural policies saved');}catch(e){notice(e.message);}};
$('access').onclick=()=>{const value=prompt('Server access token (leave empty for local access)');if(value!==null){token=value;notice('Connecting…');}};
$('connect').onclick=()=>{token=$('token').value;notice('Connecting…');};
$('layer').onchange=e=>{layer=e.target.value;if(state?.tiles)paintMap(terrain,state,layer);};
$('fit').onclick=fit;
function fit(){if(!state?.tiles)return;zoom=Math.min(canvas.width/state.width,canvas.height/state.height)*.94;ox=(canvas.width-state.width*zoom)/2;oy=(canvas.height-state.height*zoom)/2;fitted=true;}
function resize(){const r=canvas.getBoundingClientRect();canvas.width=Math.round(r.width*devicePixelRatio);canvas.height=Math.round(r.height*devicePixelRatio);if(state?.tiles)fit();}
new ResizeObserver(resize).observe(canvas);
function setupOptions(){if(optionsReady)return;optionsReady=true;for(const g of state.options.geographies){const b=document.createElement('button');b.type='button';b.dataset.geography=g.id;b.textContent=g.name;b.title=g.description;b.onclick=()=>{geography=g.id;generatePreview();};$('geography-cards').append(b);}for(const [id,list,selected] of [['biome-choice',state.options.biomes,'mixed'],['size-choice',state.options.sizes,'standard']]){for(const entry of list){const o=document.createElement('option');o.value=entry.id;o.textContent=entry.name;$(id).append(o);}$(id).value=selected;$(id).onchange=generatePreview;}powers();}
async function generatePreview(){const sequence=++previewSequence;preview=null;$('create-world').disabled=true;$('setup-status').textContent='Generating…';document.querySelectorAll('[data-geography]').forEach(b=>b.classList.toggle('active',b.dataset.geography===geography));try{const result=await command({action:'preview',geography,biome:$('biome-choice').value,size:$('size-choice').value});if(sequence!==previewSequence)return;preview=result;paintMap($('map-preview'),preview);$('preview-seed').textContent=`SEED ${preview.seed} · ${preview.width} × ${preview.height}`;$('preview-description').textContent=state.options.geographies.find(g=>g.id===geography).description;$('create-world').disabled=false;$('setup-status').textContent='Your unique world is ready.';}catch(e){if(sequence===previewSequence)$('setup-status').textContent=e.message;}}
function openSetup(){if(!state){notice('Connect to the server first.');return;}if(!dialog.open){dialog.showModal();generatePreview();}$('cancel-setup').hidden=state.setup_required;}
$('new-world').onclick=openSetup;$('reroll').onclick=generatePreview;$('cancel-setup').onclick=()=>dialog.close();
dialog.addEventListener('cancel',e=>{if(state?.setup_required)e.preventDefault();});
$('world-form').onsubmit=async e=>{e.preventDefault();if(!preview)return;const chosen=preview;$('create-world').disabled=true;try{await command({action:'new_world',geography:chosen.geography,biome:chosen.biome,size:chosen.size,seed:chosen.seed,population:Number($('population-choice').value),epoch:state.epoch});dialog.close();selected=null;fitted=false;notice('A new world begins.');}catch(error){$('setup-status').textContent=error.message;$('create-world').disabled=false;}};
function render(){ctx.fillStyle='#152d38';ctx.fillRect(0,0,canvas.width,canvas.height);if(state?.tiles){ctx.imageSmoothingEnabled=false;ctx.drawImage(terrain,ox,oy,state.width*zoom,state.height*zoom);for(const s of state.settlements){const x=ox+s.x*zoom,y=oy+s.y*zoom;ctx.fillStyle='#26343880';ctx.fillRect(x,y,zoom*2,zoom);ctx.fillStyle='#e8d6a5';ctx.fillRect(x,y-zoom*.5,zoom,zoom);ctx.fillStyle='#ad6350';ctx.fillRect(x-zoom*.15,y-zoom*.8,zoom*1.3,zoom*.4);ctx.fillStyle='#3d5960';ctx.fillRect(x+zoom*.3,y,zoom*.25,zoom*.5);}for(const caravan of state.caravans||[]){const x=ox+(caravan.x+.5)*zoom,y=oy+(caravan.y+.5)*zoom;ctx.fillStyle='#2c3439';ctx.fillRect(x-zoom*.35,y-zoom*.2,zoom*.7,zoom*.5);ctx.fillStyle='#f1c56c';ctx.fillRect(x-zoom*.25,y-zoom*.4,zoom*.5,zoom*.3);}for(const o of state.organisms){const x=ox+(o.x+.5)*zoom,y=oy+(o.y+.5)*zoom,r=Math.max(2,zoom*.24);ctx.fillStyle='#12343b99';ctx.fillRect(x-r,y-r+2,r*2.5,r*2);ctx.fillStyle=o.kind==='human'?'#ffe5aa':o.kind==='predator'?'#e99071':'#f1efd6';ctx.fillRect(x-r,y-r,r*2,r*1.5);if(o.kind==='human'){ctx.fillStyle=['#61c6c0','#ce869e','#dda756','#8db771','#8a9ad7'][o.culture%5];ctx.fillRect(x-r,y,r*2,r*1.5);}else{ctx.fillStyle='#233b41';ctx.fillRect(x-r,y+r*.3,r*.4,r);ctx.fillRect(x+r*.5,y+r*.3,r*.4,r);}}if(selected){ctx.strokeStyle='#fff0b0';ctx.lineWidth=2;ctx.strokeRect(ox+selected.x*zoom-2,oy+selected.y*zoom-2,zoom+4,zoom+4);}if(hover&&tool!=='inspect'){ctx.strokeStyle='#fff4cebb';ctx.lineWidth=1.5;ctx.beginPath();ctx.arc(ox+(hover.x+.5)*zoom,oy+(hover.y+.5)*zoom,Number($('radius').value)*zoom,0,Math.PI*2);ctx.stroke();}}requestAnimationFrame(render);}
function point(e){const r=canvas.getBoundingClientRect();return[(e.clientX-r.left)*devicePixelRatio,(e.clientY-r.top)*devicePixelRatio];}
canvas.onpointerdown=e=>{const[x,y]=point(e);dragging={x,y,ox,oy,moved:false};canvas.setPointerCapture(e.pointerId);};
canvas.onpointermove=e=>{const[x,y]=point(e);hover={x:Math.floor((x-ox)/zoom),y:Math.floor((y-oy)/zoom)};if(!dragging)return;if(Math.hypot(x-dragging.x,y-dragging.y)>5)dragging.moved=true;if(dragging.moved){ox=dragging.ox+x-dragging.x;oy=dragging.oy+y-dragging.y;}};
canvas.onpointerleave=()=>hover=null;
canvas.onpointerup=async e=>{if(!dragging)return;const click=!dragging.moved;dragging=null;if(!click||!state?.tiles)return;const[px,py]=point(e),x=Math.floor((px-ox)/zoom),y=Math.floor((py-oy)/zoom);if(x<0||y<0||x>=state.width||y>=state.height)return;if(tool==='inspect'){selected={x,y};inspect();return;}if(casting)return;casting=true;try{const result=await command({action:'tool',tool,x,y,radius:Number($('radius').value),strength:Number($('strength').value)});notice(result.affected?`${result.tiles_changed} tiles changed · ${result.spawned} spawned · ${result.organisms_changed} altered · ${result.killed} removed · ${result.settlements_removed} settlements destroyed`:'No effect here. Check terrain, population cap, or creatures in the brush.');}catch(error){notice(error.message);}finally{casting=false;}};
canvas.onpointercancel=()=>dragging=null;
canvas.addEventListener('wheel',e=>{e.preventDefault();const[x,y]=point(e),old=zoom;zoom=Math.max(2,Math.min(100,zoom*Math.exp(-e.deltaY*.001)));ox=x-(x-ox)*zoom/old;oy=y-(y-oy)*zoom/old;},{passive:false});
function inspect(){if(!selected||!state?.tiles)return;const{x,y}=selected,o=state.organisms.find(a=>a.x===x&&a.y===y),t=state.tiles[y*state.width+x];$('inspector').innerHTML=o?`<strong>${o.kind.toUpperCase()} #${o.id}</strong><br>Energy ${o.energy.toFixed(1)} · Age ${o.age}<br>Generation ${o.generation} · Size ${o.size.toFixed(2)} · Mate signal ${o.mate_signal.toFixed(2)}<br>Parents ${o.parent_a||"—"} / ${o.parent_b||"—"} · Ideal temperature ${Math.round(o.thermal_opt*100)}%<br>Household ${o.household||"—"} · Work ${o.occupation}<br>Neural updates ${o.updates}<br>Culture ${o.culture||'—'} · Wood ${o.wood.toFixed(1)}`:`<strong>${biomeNames[t[8]]||'Land'} · ${x}, ${y}</strong><br>Elevation ${t[0].toFixed(2)} · Temperature ${Math.round(t[7]*100)}%<br>Moisture ${Math.round(t[1]*100)}% · Food ${Math.round(t[2]*100)}%<br>Trees ${Math.round(t[3]*100)}% · Runoff ${Math.round((t[9]||0)*100)}%<br>Plant cohorts ${t[11]||0} grass · ${t[12]||0} trees<br>Lava ${Math.round((t[10]||0)*100)}% · Minerals ${t[4].toFixed(2)}<br>Soil ${Math.round(t[6]*100)}% · Nutrients ${Math.round((t[14]||0)*100)}%<br>Litter ${Math.round((t[15]||0)*100)}% · Road ${Math.round((t[13]||0)*100)}%`;}
async function poll(){try{const r=await fetch('/api/state',{headers:{Authorization:`Bearer ${token}`}});if(!r.ok)throw Error(r.status===401?'Access token required—use Access above':'Server unavailable');state=await r.json();setupOptions();const viewer=state.runtime.role==='viewer';for(const id of ['new-world','pause','speed','save','power-group','radius','strength'])$(id).disabled=viewer;document.querySelectorAll('[data-tool]').forEach(b=>b.disabled=viewer);if(viewer)setTool('inspect');$('connection').textContent=state.runtime.error?'Simulation stopped':viewer?'● Spectator':'● Connected';if(state.setup_required){if(viewer){if(dialog.open)dialog.close();return;}openSetup();return;}if(epoch!==state.epoch){epoch=state.epoch;selected=null;fitted=false;}$('clock').textContent=`Age ${state.tick}`;$('seed').textContent=`SEED ${state.seed}`;$('population').textContent=state.stats.population.toLocaleString();$('pause').textContent=state.runtime.paused?'Resume':'Pause';$('speed').value=state.runtime.speed;const stats=[['Humans',state.stats.counts.human||0],['Settlements',state.settlements.length],['Households',state.stats.households],['Caravans',state.stats.caravans],['Births',state.stats.births],['Generation',state.stats.generation],['Cultures',state.stats.cultures],['Ecotypes',state.stats.ecotypes],['Mate traits',state.stats.mate_types],['Mating isolation',state.stats.mate_encounters?Math.round(state.stats.mate_rejections/state.stats.mate_encounters*100)+'%':'—'],['Two-parent births',state.stats.sexual_births],['Learning steps',state.stats.training.toLocaleString()]];$('stats').innerHTML=stats.map(([k,v])=>`<div class="stat"><strong>${v}</strong><span>${k}</span></div>`).join('');$('events').replaceChildren(...state.events.slice(0,6).map(e=>{const p=document.createElement('p'),s=document.createElement('small');s.textContent=`AGE ${e.tick}`;p.append(s,document.createTextNode(e.text));return p;}));$('runtime').textContent=`${state.runtime.tick_ms} ms / tick · ${state.runtime.workers} CPU workers · ${state.runtime.device.toUpperCase()}`;paintMap(terrain,state,layer);if(!fitted)fit();inspect();}catch(e){$('connection').textContent=e.message;}finally{setTimeout(poll,500);}}
resize();render();poll();
